#!/bin/sh

set -e
set -x

aclocal
case "${OSTYPE}" in
	darwin*)
		glibtoolize --force
		;;
	*)
		libtoolize --force
		;;
esac
autoheader
automake -a
autoconf
./configure --prefix=/usr
make
make install
cd perl
sh ./build

