#!/bin/sh

set -e
set -x

aclocal || exit 1
libtoolize --force || exit 1
automake-1.9 -a || exit 1
autoconf || exit 1
./configure || exit 1
make || exit 1
make install  || exit 1
cd perl
sh ./build || exit 1

